# Target connection is the Azure Artifacts package link, example: https://pkgs.dev.azure.com/<MY-ORG>
AZURE_ARTIFACTS_TARGET_CONNECTION: ''

# The connection name is up to you. It is a name for the connection to be set within AzureML, example: altaml-project1
AZURE_ARTIFACTS_CONNECTION_NAME: ''