data_processing_settings:
  input_data_paths:
    path_1: "./data/download/raw_data/grd_data_download/grd_data_download.feather"
    path_2: "./data/download/raw_data/tmp_data_download/tmp_data_download.feather"
    path_3: "./data/download/raw_data/tur_data_download/tur_data_download.feather"
  # The following columns are removed using domain knowledge
  drop_columns: { "common": [
          "wopr_id",
          "sub_circuit_uid",
          "pad",
          "nn2",
          "asset_group_uid",
          "nn1",
          "equipment_uid",
          "circuit_uid",
          "Column1",
          "is_operational",
          "kks_id",
          "longitude",
          "asset_name",
          "site_uid",
          "latitude",
          "elevation",
          "equipment_model_uid",
        ], "grd": [
          "cosphi_last",
          "cosphi_max",
          "cosphi_min",
          "cosphi_std",
          "current_a_max",
          "current_a_min",
          "current_a_std",
          "current_b_max",
          "current_b_min",
          "current_b_std",
          "current_c_max",
          "current_c_min",
          "current_c_std",
          "frequency_max",
          "frequency_min",
          "frequency_std",
          "power_act_last",
          "power_act_max",
          "power_act_min",
          "power_act_std",
          "power_quality_last",
          "reactive_power_last",
          "reactive_power",
          "reactive_power_max",
          "reactive_power_min",
          "reactive_power_std",
          "voltage_a_max",
          "voltage_a_min",
          "voltage_a_std",
          "voltage_b_max",
          "voltage_b_min",
          "voltage_b_std",
          "voltage_c_max",
          "voltage_c_min",
          "voltage_c_std",
          "reg_state_last",
        ], "tmp": [
          "brake_temp_max",
          "brake_temp_min",
          "brake_temp_std",
          "converter_w_temp_max",
          "converter_w_temp_min",
          "converter_w_temp_std",
          "gearbox_bearing_ims_gen_side_temp_max",
          "gearbox_bearing_ims_gen_side_temp_min",
          "gearbox_bearing_ims_gen_side_temp_std",
          "gearbox_bearing_ims_rotor_side_temp_max",
          "gearbox_bearing_ims_rotor_side_temp_min",
          "gearbox_bearing_ims_rotor_side_temp_std",
          "gearbox_hs_bearing_max",
          "gearbox_hs_bearing_min",
          "gearbox_hs_bearing_std",
          "gearbox_oil_temp_max",
          "gearbox_oil_temp_min",
          "gearbox_oil_temp_std",
          "gen_bearing_drive_end_temp_max",
          "gen_bearing_drive_end_temp_min",
          "gen_bearing_drive_end_temp_std",
          "gen_bearing_non_drive_end_temp_max",
          "gen_bearing_non_drive_end_temp_min",
          "gen_bearing_non_drive_end_temp_std",
          "gen_temp_1u1_max",
          "gen_temp_1u1_min",
          "gen_temp_1u1_std",
          "gen_temp_1v1_max",
          "gen_temp_1v1_min",
          "gen_temp_1v1_std",
          "gen_temp_1w1_max",
          "gen_temp_1w1_min",
          "gen_temp_1w1_std",
          "generator_hs_bearing_max",
          "generator_hs_bearing_min",
          "generator_hs_bearing_std",
          "grid_filter_b1_temp_max",
          "grid_filter_b1_temp_min",
          "grid_filter_b1_temp_std",
          "grid_filter_b2_temp_max",
          "grid_filter_b2_temp_min",
          "grid_filter_b2_temp_std",
          "grid_filter_b3_temp_max",
          "grid_filter_b3_temp_min",
          "grid_filter_b3_temp_std",
          "hub_temp_max",
          "hub_temp_min",
          "hub_temp_std",
          "hydraulic_oil_temp_max",
          "hydraulic_oil_temp_min",
          "hydraulic_oil_temp_std",
          "int_cabinet_temp_a1_max",
          "int_cabinet_temp_a1_min",
          "int_cabinet_temp_a1_std",
          "int_cabinet_temp_a9_max",
          "int_cabinet_temp_a9_min",
          "int_cabinet_temp_a9_std",
          "left_cabinet_temp_a3_max",
          "left_cabinet_temp_a3_min",
          "left_cabinet_temp_a3_std",
          "main_bearing_temp_max",
          "main_bearing_temp_min",
          "main_bearing_temp_std",
          "nacelle_temp_max",
          "nacelle_temp_min",
          "nacelle_temp_std",
          "reactor_phase_u_temp_max",
          "reactor_phase_u_temp_min",
          "reactor_phase_u_temp_std",
          "reactor_phase_v_temp_max",
          "reactor_phase_v_temp_min",
          "reactor_phase_v_temp_std",
          "reactor_phase_w_temp_max",
          "reactor_phase_w_temp_min",
          "reactor_phase_w_temp_std",
          "right_cabinet_temp_a3_max",
          "right_cabinet_temp_a3_min",
          "right_cabinet_temp_a3_std",
          "temp_max",
          "temp_min",
          "temp_std",
        ], "tur": [
          "gen_speed_max",
          "gen_speed_min",
          "gen_speed_std"
          "nacelle_position_2_max",
          "nacelle_position_2_min",
          "nacelle_position_2_std",
          "nacelle_position_3_max",
          "nacelle_position_3_min",
          "nacelle_position_3_std",
          "nacelle_position_max",
          "nacelle_position_min",
          "nacelle_position_std",
          "pitch_a_act_max",
          "pitch_a_act_min",
          "pitch_a_act_std",
          "pitch_a_ref",
          "pitch_a_ref_max",
          "pitch_a_ref_min",
          "pitch_a_ref_std",
          "pitch_b_act_max",
          "pitch_b_act_min",
          "pitch_b_act_std",
          "pitch_b_ref",
          "pitch_b_ref_max",
          "pitch_b_ref_min",
          "pitch_b_ref_std",
          "pitch_c_act_max",
          "pitch_c_act_min",
          "pitch_c_act_std",
          "pitch_c_ref",
          "pitch_c_ref_max",
          "pitch_c_ref_min",
          "pitch_c_ref_std",
          "pitch_set_max",
          "pitch_set_min",
          "pitch_set_std",
          "primary_anemometer_max",
          "primary_anemometer_min",
          "primary_anemometer_std",
          "primary_windspeed_max",
          "primary_windspeed_min",
          "primary_windspeed_std",
          "rotor_rpm_max",
          "rotor_rpm_min",
          "rotor_rpm_std",
          "secondary_anemometer_max",
          "secondary_anemometer_min",
          "secondary_anemometer_std",
          "secondary_windspeed_max",
          "secondary_windspeed_min",
          "secondary_windspeed_std",
          "tet_an_freq",
          "tet_an_freq_max",
          "tet_an_freq_min",
          "tet_an_freq_std",
          "tower_frequency_max",
          "tower_frequency_min",
          "tower_frequency_std",
          "windspeed_act_max",
          "windspeed_act_min",
          "windspeed_act_std",
          "ts_cur",
        ] }